# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Bearing
                                 A QGIS plugin
 Menghitung Bearing dengan memasukan nilai sudut Azimuth dan Jarak
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-24
        copyright            : (C) 2023 by Muhamad Yusuf
        email                : yusfmuhamad176@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Bearing class from file Bearing.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Perhitungan_Bearing import Bearing
    return Bearing(iface)
